#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GProject.Resource", IsApplication=true)]

namespace GProject
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int backgorund2 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background3 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int corner = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int corneracikmavi = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int cornerbeyaz = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int cornerbutton = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int cornermavi = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int logo_bordered = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int TimeTable = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050022
			public const int FacultyStaff = 2131034146;
			
			// aapt resource value: 0x7f050009
			public const int btnAddUser = 2131034121;
			
			// aapt resource value: 0x7f050032
			public const int btnClassBasedSearchR = 2131034162;
			
			// aapt resource value: 0x7f050024
			public const int btnClassSearch = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int btnCourseSearch = 2131034149;
			
			// aapt resource value: 0x7f050035
			public const int btnCourseSearchR = 2131034165;
			
			// aapt resource value: 0x7f050027
			public const int btnEmptySearch = 2131034151;
			
			// aapt resource value: 0x7f050034
			public const int btnEmptySearchR = 2131034164;
			
			// aapt resource value: 0x7f05002c
			public const int btnLogin = 2131034156;
			
			// aapt resource value: 0x7f050029
			public const int btnSendMail = 2131034153;
			
			// aapt resource value: 0x7f05000a
			public const int btnShowUsers = 2131034122;
			
			// aapt resource value: 0x7f050026
			public const int btnTimeSearch = 2131034150;
			
			// aapt resource value: 0x7f050033
			public const int btnTimeSearchR = 2131034163;
			
			// aapt resource value: 0x7f050036
			public const int comboClassNames = 2131034166;
			
			// aapt resource value: 0x7f05003f
			public const int comboClassNamesR = 2131034175;
			
			// aapt resource value: 0x7f050041
			public const int comboCourseSearch = 2131034177;
			
			// aapt resource value: 0x7f050043
			public const int comboCourseSearchR = 2131034179;
			
			// aapt resource value: 0x7f050046
			public const int comboDays = 2131034182;
			
			// aapt resource value: 0x7f05004c
			public const int comboDaysEmpty = 2131034188;
			
			// aapt resource value: 0x7f050050
			public const int comboDaysEmptyR = 2131034192;
			
			// aapt resource value: 0x7f050049
			public const int comboDaysR = 2131034185;
			
			// aapt resource value: 0x7f05004e
			public const int comboDurationEmpty = 2131034190;
			
			// aapt resource value: 0x7f050052
			public const int comboDurationEmptyR = 2131034194;
			
			// aapt resource value: 0x7f050014
			public const int comboNewFacultyName = 2131034132;
			
			// aapt resource value: 0x7f050012
			public const int comboNewType = 2131034130;
			
			// aapt resource value: 0x7f050047
			public const int comboTimes = 2131034183;
			
			// aapt resource value: 0x7f05004d
			public const int comboTimesEmpty = 2131034189;
			
			// aapt resource value: 0x7f050051
			public const int comboTimesEmptyR = 2131034193;
			
			// aapt resource value: 0x7f05004a
			public const int comboTimesR = 2131034186;
			
			// aapt resource value: 0x7f050016
			public const int comboUsers = 2131034134;
			
			// aapt resource value: 0x7f050013
			public const int facultyLayout = 2131034131;
			
			// aapt resource value: 0x7f05003e
			public const int gridClass = 2131034174;
			
			// aapt resource value: 0x7f050040
			public const int gridClassR = 2131034176;
			
			// aapt resource value: 0x7f050042
			public const int gridCourse = 2131034178;
			
			// aapt resource value: 0x7f050044
			public const int gridCourseR = 2131034180;
			
			// aapt resource value: 0x7f050048
			public const int gridDayTime = 2131034184;
			
			// aapt resource value: 0x7f05004b
			public const int gridDayTimeR = 2131034187;
			
			// aapt resource value: 0x7f05004f
			public const int gridEmpty = 2131034191;
			
			// aapt resource value: 0x7f050053
			public const int gridEmptyR = 2131034195;
			
			// aapt resource value: 0x7f05002a
			public const int imageView1 = 2131034154;
			
			// aapt resource value: 0x7f050045
			public const int layout1 = 2131034181;
			
			// aapt resource value: 0x7f05002d
			public const int lblForgot = 2131034157;
			
			// aapt resource value: 0x7f05001a
			public const int lblUserEmail = 2131034138;
			
			// aapt resource value: 0x7f05001d
			public const int lblUserFaculty = 2131034141;
			
			// aapt resource value: 0x7f050023
			public const int lblUserFacultyName = 2131034147;
			
			// aapt resource value: 0x7f050017
			public const int lblUserID = 2131034135;
			
			// aapt resource value: 0x7f05001f
			public const int lblUserIDMenu = 2131034143;
			
			// aapt resource value: 0x7f05002f
			public const int lblUserIDMenuR = 2131034159;
			
			// aapt resource value: 0x7f050004
			public const int lblUserIdAdmin = 2131034116;
			
			// aapt resource value: 0x7f050018
			public const int lblUserName = 2131034136;
			
			// aapt resource value: 0x7f050005
			public const int lblUserNameA = 2131034117;
			
			// aapt resource value: 0x7f050020
			public const int lblUserNameF = 2131034144;
			
			// aapt resource value: 0x7f050030
			public const int lblUserNameR = 2131034160;
			
			// aapt resource value: 0x7f05001b
			public const int lblUserRecEmail = 2131034139;
			
			// aapt resource value: 0x7f050019
			public const int lblUserSurname = 2131034137;
			
			// aapt resource value: 0x7f050006
			public const int lblUserSurnameA = 2131034118;
			
			// aapt resource value: 0x7f050021
			public const int lblUserSurnameF = 2131034145;
			
			// aapt resource value: 0x7f050031
			public const int lblUserSurnameR = 2131034161;
			
			// aapt resource value: 0x7f05001c
			public const int lblUserType = 2131034140;
			
			// aapt resource value: 0x7f050007
			public const int lblUserTypeMenu = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int linearLayout1 = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout2 = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int linearLayout3 = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout4 = 2131034112;
			
			// aapt resource value: 0x7f05001e
			public const int relativeLayout1 = 2131034142;
			
			// aapt resource value: 0x7f050011
			public const int textView1 = 2131034129;
			
			// aapt resource value: 0x7f050003
			public const int textView2 = 2131034115;
			
			// aapt resource value: 0x7f05000f
			public const int txtNewEmailddres = 2131034127;
			
			// aapt resource value: 0x7f05000b
			public const int txtNewID = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int txtNewName = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int txtNewPassword = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int txtNewRecoveryEmailAdress = 2131034128;
			
			// aapt resource value: 0x7f05000d
			public const int txtNewSurname = 2131034125;
			
			// aapt resource value: 0x7f05002e
			public const int txtPassword = 2131034158;
			
			// aapt resource value: 0x7f050015
			public const int txtSearchName = 2131034133;
			
			// aapt resource value: 0x7f050028
			public const int txtUserEmail = 2131034152;
			
			// aapt resource value: 0x7f05002b
			public const int txtUserID = 2131034155;
			
			// aapt resource value: 0x7f050037
			public const int txtView1 = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int txtView2 = 2131034168;
			
			// aapt resource value: 0x7f050039
			public const int txtView3 = 2131034169;
			
			// aapt resource value: 0x7f05003a
			public const int txtView4 = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int txtView5 = 2131034171;
			
			// aapt resource value: 0x7f05003c
			public const int txtView6 = 2131034172;
			
			// aapt resource value: 0x7f05003d
			public const int txtView7 = 2131034173;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Admin_Form = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Admin_Form_ADD = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Admin_Form_Show = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Faculty_Form = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Forgot_Form = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Login_Form = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Rectorate_Form = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Time_TableClass = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Time_TableClassR = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Time_TableCourse = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Time_TableCourseR = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Time_TableDayTime = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Time_TableDayTimeR = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Time_TableEmpty = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Time_TableEmptyR = 2130903054;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
